name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image 
      run: |
        docker build -t mabirhire1/kodecamp-app:latest .
        docker push mabirhire1/kodecamp-app:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy deployment file to remote server
      run: |
        echo ${GITHUB_WORKSPACE}/.github/main/k8s/deployment.yaml
        scp -o StrictHostKeyChecking=no ${GITHUB_WORKSPACE}/.github/main/k8s/deployment.yaml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "kubectl apply -f /home/ubuntu/deployment.yaml"
    
       
